# Generated by Django 3.1 on 2020-09-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='teacheruid',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
