# Generated by Django 3.1 on 2020-09-08 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20200908_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='uploads/profilepics'),
        ),
    ]
