# Generated by Django 3.1 on 2020-09-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20200908_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='image',
        ),
    ]
