# Generated by Django 3.1 on 2020-09-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_remove_content_contentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='courseuid',
        ),
        migrations.AddField(
            model_name='content',
            name='cuid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
