# Generated by Django 3.1 on 2020-09-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_auto_20200910_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursecategory',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
