# Generated by Django 3.1 on 2020-09-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_auto_20200910_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='useruid',
            field=models.IntegerField(default=None),
        ),
    ]
