# Generated by Django 3.1 on 2020-09-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_auto_20200910_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='isenrolled',
            field=models.BooleanField(default=False),
        ),
    ]
