# Generated by Django 3.1 on 2020-09-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_subscription_isenrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='createdby',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='content',
            name='createdbyid',
            field=models.IntegerField(default=0),
        ),
    ]
