# Generated by Django 3.1 on 2020-09-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_auto_20200910_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='createdby',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
