# Generated by Django 3.1 on 2020-09-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_course_createdby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
