# Generated by Django 3.1 on 2020-09-15 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseimages',
            field=models.ImageField(blank=True, upload_to='uploads/coursepics'),
        ),
        migrations.AddField(
            model_name='course',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 19, 2, 34, 907660)),
        ),
    ]
