# Generated by Django 3.1 on 2020-09-17 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_auto_20200915_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=50)),
                ('star', models.IntegerField(default=0)),
                ('courseuid', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 19, 0, 47, 396827)),
        ),
    ]
