# Generated by Django 3.1 on 2020-09-17 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0018_auto_20200917_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='star',
        ),
        migrations.AlterField(
            model_name='course',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 22, 43, 57, 58156)),
        ),
    ]
