# Generated by Django 3.1 on 2020-09-21 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_auto_20200917_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseimages',
            new_name='courseimage',
        ),
        migrations.AlterField(
            model_name='course',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 18, 23, 54, 134343)),
        ),
    ]
